language: python

os:
  - linux

python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  - GTEST_ROOT="$HOME/.local"

before_install:
  - travis/install_packages.sh
  - travis/install_pytorch.sh
  - travis/install_gtest.sh

script:
  - travis/build.sh
  - travis/test.sh

notifications:
  email:
    on_success: change
    on_failure: always
