language: python

os:
  - linux

python:
  - "2.7"
  - "3.5"
  - "3.6"

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

env:
  - GTEST_ROOT="$HOME/.local"
  - CC=gcc-4.9 CXX=g++-4.9
  - CC=clang CXX=clang++

before_install:
  - travis/install_packages.sh
  - travis/install_pytorch.sh
  - travis/install_gtest.sh

script:
  - travis/build.sh
  - travis/test.sh

after_failure:
  - cat build/Testing/Temporary/LastTest.log

notifications:
  email:
    on_success: change
    on_failure: always
