dist: bionic
sudo: true

language: python

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

python:
  - 3.6
  - 3.7
  - 3.8

env:
  global:
    - GTEST_ROOT="$HOME/.local"
  matrix:
    - CC=gcc-7 CXX=g++-7 TORCH_PIP_PACKAGE="torch==1.4.0"

# Add tests with additional compilers
matrix:
  include:
    - python: 3.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
      env: CC=gcc-6 CXX=g++-6 TORCH_PIP_PACKAGE="torch==1.4.0"


before_install:
  # Upgrade PIP to latest version, in order to support --progres-bar
  - pip install -U pip
  # Install prerequisites.
  - pip install --progress-bar off -r <(sed -r 's/^torch.*$//g;/^$/d' requirements.txt)
  - pip install $TORCH_PIP_PACKAGE --progress-bar off

script:
  - travis/build.sh
  - travis/test.sh

notifications:
  email:
    on_success: change
    on_failure: always
