dist: trusty
sudo: false

language: python

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  global:
    - GTEST_ROOT="$HOME/.local"
  matrix:
    - CC=gcc-4.9 CXX=g++-4.9

# Add tests with additional compilers
matrix:
  include:
    - python: 3.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
      env: CC=gcc-5 CXX=g++-5
    - python: 3.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
      env: CC=gcc-6 CXX=g++-6

before_install:
  - travis/install_packages.sh
  - travis/install_pytorch.sh
  - travis/install_gtest.sh

script:
  - travis/build.sh
  - travis/test.sh

after_failure:
  - cat build/Testing/Temporary/LastTest.log
  - find build/pytorch/inst -name "*.so" | xargs -n1 nm -C | awk '$1 == "U"'
  - find build/pytorch/inst -name "*.so" | xargs -n1 ldd

notifications:
  email:
    on_success: change
    on_failure: always
